behaviors:
  TowerAgent:
    trainer_type: ppo
    hyperparameters:
      batch_size: 64
      buffer_size: 512
      learning_rate: 0.005
      beta: 0.02
      epsilon: 0.2
      lambd: 0.9
      num_epoch: 1
      learning_rate_schedule: linear
    network_settings:
      normalize: true
      hidden_units: 32
      num_layers: 2
      vis_encode_type: simple
      continuous_actions: 2
    reward_signals:
      extrinsic:
        gamma: 0.95
        strength: 0.6   
    keep_checkpoints: 1
    max_steps: 30000      
    time_horizon: 512
    summary_freq: 1000
